import React,{useEffect,useMemo,useState} from 'react'
import {cloudEnabled,supabase} from './supabase'

const LOCAL_KEY='baking_library_official_v1'
const categories=['Bánh mì','Bông lan','Cheesecake','Lava / Nhân','Cookie / Tart','Kem / Bánh lạnh','Bánh Việt','Bánh trung thu','Đồ uống','Khác']
const empty={id:'',name:'',category:'Bánh mì',source:'',author:'',version:'V1',yield_text:'',time_text:'',tags:'',ingredients:'',steps:'',notes:'',original_text:'',favorite:false,tested:false,rating:5}

export default function App(){
 const[user,setUser]=useState(null),[recipes,setRecipes]=useState([]),[query,setQuery]=useState(''),[category,setCategory]=useState('Tất cả')
 const[form,setForm]=useState(empty),[files,setFiles]=useState([]),[formOpen,setFormOpen]=useState(false),[detail,setDetail]=useState(null)
 const[authMode,setAuthMode]=useState('login'),[auth,setAuth]=useState({email:'',password:''}),[message,setMessage]=useState('')

 useEffect(()=>{
  if(!cloudEnabled){const saved=JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]');setRecipes(saved.length?saved:sample());return}
  supabase.auth.getSession().then(({data})=>setUser(data.session?.user||null))
  const{data:sub}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>sub.subscription.unsubscribe()
 },[])
 useEffect(()=>{if(cloudEnabled&&user)loadCloud()},[user])
 useEffect(()=>{if(!cloudEnabled)localStorage.setItem(LOCAL_KEY,JSON.stringify(recipes))},[recipes])

 async function loadCloud(){const{data,error}=await supabase.from('recipes').select('*,recipe_images(*)').order('created_at',{ascending:false});if(error)setMessage(error.message);else setRecipes(data||[])}
 async function submitAuth(e){e.preventDefault();setMessage('');const req=authMode==='login'?supabase.auth.signInWithPassword(auth):supabase.auth.signUp(auth);const{error}=await req;if(error)setMessage(error.message);else if(authMode==='register')setMessage('Đã tạo tài khoản. Hãy kiểm tra email nếu được yêu cầu xác nhận.')}
 async function saveRecipe(e){e.preventDefault();setMessage('Đang lưu...');try{
  if(!cloudEnabled){const item={...form,id:form.id||crypto.randomUUID(),images:files.length?await Promise.all(files.map(toDataUrl)):(form.images||[]),created_at:form.created_at||new Date().toISOString()};setRecipes(p=>form.id?p.map(r=>r.id===form.id?item:r):[item,...p]);closeForm();setMessage('');return}
  const payload={name:form.name,category:form.category,source:form.source,author:form.author,version:form.version,yield_text:form.yield_text,time_text:form.time_text,tags:form.tags,ingredients:form.ingredients,steps:form.steps,notes:form.notes,original_text:form.original_text,favorite:form.favorite,tested:form.tested,rating:Number(form.rating),owner_id:user.id}
  let id=form.id;if(id){const{error}=await supabase.from('recipes').update(payload).eq('id',id);if(error)throw error}else{const{data,error}=await supabase.from('recipes').insert(payload).select().single();if(error)throw error;id=data.id}
  for(const file of files){const path=`${user.id}/${id}/${crypto.randomUUID()}-${file.name}`;const{error:up}=await supabase.storage.from('recipe-images').upload(path,file);if(up)throw up;const{data:pub}=supabase.storage.from('recipe-images').getPublicUrl(path);const{error:im}=await supabase.from('recipe_images').insert({recipe_id:id,owner_id:user.id,image_url:pub.publicUrl,storage_path:path});if(im)throw im}
  await loadCloud();closeForm();setMessage('')
 }catch(err){setMessage(err.message||String(err))}}
 async function removeRecipe(id){if(!confirm('Xóa công thức này?'))return;if(!cloudEnabled){setRecipes(p=>p.filter(r=>r.id!==id));setDetail(null);return}const{error}=await supabase.from('recipes').delete().eq('id',id);if(error)setMessage(error.message);else{await loadCloud();setDetail(null)}}
 async function toggleFavorite(r){if(!cloudEnabled){setRecipes(p=>p.map(x=>x.id===r.id?{...x,favorite:!x.favorite}:x));setDetail(d=>d?{...d,favorite:!d.favorite}:d);return}await supabase.from('recipes').update({favorite:!r.favorite}).eq('id',r.id);await loadCloud();setDetail(d=>d?{...d,favorite:!d.favorite}:d)}
 function openNew(){setForm(empty);setFiles([]);setFormOpen(true)}
 function openEdit(r){setForm({...empty,...r});setFiles([]);setFormOpen(true);setDetail(null)}
 function closeForm(){setFormOpen(false);setForm(empty);setFiles([])}
 const filtered=useMemo(()=>recipes.filter(r=>[r.name,r.category,r.source,r.author,r.tags,r.ingredients,r.steps].join(' ').toLowerCase().includes(query.toLowerCase())&&(category==='Tất cả'||r.category===category)),[recipes,query,category])

 if(cloudEnabled&&!user)return <div className="auth-page"><form className="auth-card" onSubmit={submitAuth}><div className="logo">🍰</div><h1>Baking Library</h1><p>Đăng nhập để đồng bộ trên điện thoại và máy tính.</p><input type="email" placeholder="Email" required value={auth.email} onChange={e=>setAuth({...auth,email:e.target.value})}/><input type="password" placeholder="Mật khẩu" required value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})}/><button className="primary">{authMode==='login'?'Đăng nhập':'Tạo tài khoản'}</button><button type="button" className="secondary" onClick={()=>setAuthMode(authMode==='login'?'register':'login')}>{authMode==='login'?'Chưa có tài khoản':'Đã có tài khoản'}</button>{message&&<div className="notice">{message}</div>}</form></div>

 return <div><header><div className="top"><div className="logo small">🍰</div><div><h1>Baking Library</h1><small>{cloudEnabled?'Cloud Edition':'Chế độ dùng thử trên máy'}</small></div><div className="spacer"/>{cloudEnabled&&<button className="secondary" onClick={()=>supabase.auth.signOut()}>Đăng xuất</button>}<button className="primary" onClick={openNew}>+ Thêm công thức</button></div><div className="searchbar"><input placeholder="Tìm tên bánh, nguyên liệu hoặc từ khóa..." value={query} onChange={e=>setQuery(e.target.value)}/><div className="chips">{['Tất cả',...categories].map(c=><button key={c} className={category===c?'chip active':'chip'} onClick={()=>setCategory(c)}>{c}</button>)}</div></div></header>
 <main><section className="hero"><div><h2>Mọi công thức của bạn, trong một nơi thật đẹp.</h2><p>Nhập một lần, nhiều ảnh, tìm nhanh và đồng bộ trên mọi thiết bị.</p></div><div className="hero-art">🧁</div></section><section className="stats"><Stat label="Tổng công thức" value={recipes.length}/><Stat label="Yêu thích" value={recipes.filter(r=>r.favorite).length}/><Stat label="Đã thử" value={recipes.filter(r=>r.tested).length}/><Stat label="Có ảnh" value={recipes.filter(r=>imagesOf(r).length).length}/></section>{message&&<div className="notice">{message}</div>}<section className="grid">{filtered.map(r=><Card key={r.id} recipe={r} onOpen={()=>setDetail(r)}/>)}</section>{!filtered.length&&<div className="empty">Chưa có công thức phù hợp.</div>}</main>
 {formOpen&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>{form.id?'Sửa công thức':'Thêm công thức'}</h2><button onClick={closeForm}>✕</button></div><form onSubmit={saveRecipe} className="form"><Field label="Tên công thức"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Nhóm bánh"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Nguồn"><input value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></Field><Field label="Tác giả"><input value={form.author} onChange={e=>setForm({...form,author:e.target.value})}/></Field><Field label="Phiên bản"><input value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/></Field><Field label="Đánh giá"><select value={form.rating} onChange={e=>setForm({...form,rating:e.target.value})}>{[5,4,3,2,1].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Khẩu phần"><input value={form.yield_text} onChange={e=>setForm({...form,yield_text:e.target.value})}/></Field><Field label="Thời gian / Nhiệt độ"><input value={form.time_text} onChange={e=>setForm({...form,time_text:e.target.value})}/></Field><Field full label="Từ khóa"><input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></Field><Field full label="Nguyên liệu"><textarea value={form.ingredients} onChange={e=>setForm({...form,ingredients:e.target.value})}/></Field><Field full label="Cách làm — mỗi bước xuống dòng"><textarea value={form.steps} onChange={e=>setForm({...form,steps:e.target.value})}/></Field><Field full label="Lưu ý / Kinh nghiệm"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><Field full label="Nội dung gốc"><textarea value={form.original_text} onChange={e=>setForm({...form,original_text:e.target.value})}/></Field><Field full label="Chọn nhiều ảnh"><input type="file" accept="image/*" multiple onChange={e=>setFiles([...e.target.files])}/></Field><label className="check"><input type="checkbox" checked={form.tested} onChange={e=>setForm({...form,tested:e.target.checked})}/> Đã thử</label><label className="check"><input type="checkbox" checked={form.favorite} onChange={e=>setForm({...form,favorite:e.target.checked})}/> Yêu thích</label><div className="form-actions"><button type="button" className="secondary" onClick={closeForm}>Hủy</button><button className="primary">Lưu công thức</button></div></form></div></div>}
 {detail&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>Chi tiết công thức</h2><button onClick={()=>setDetail(null)}>✕</button></div><div className="detail"><div className="detail-hero"><div className="detail-cover">{imagesOf(detail)[0]?<img src={imagesOf(detail)[0]}/>:'🍰'}</div><div><span className="pill">{detail.category}</span><h1>{detail.name}</h1><p>{'★'.repeat(Number(detail.rating)||0)}{'☆'.repeat(5-(Number(detail.rating)||0))}</p><p className="muted">Phiên bản: {detail.version||'V1'}<br/>Nguồn: {detail.source||'—'}<br/>Tác giả: {detail.author||'—'}<br/>Khẩu phần: {detail.yield_text||'—'}<br/>Thời gian/Nhiệt độ: {detail.time_text||'—'}</p><div className="detail-actions"><button className="primary" onClick={()=>openEdit(detail)}>Sửa</button><button className="secondary" onClick={()=>toggleFavorite(detail)}>❤️</button><button className="danger" onClick={()=>removeRecipe(detail.id)}>Xóa</button></div></div></div>{!!imagesOf(detail).length&&<section><h3>Album ảnh</h3><div className="gallery">{imagesOf(detail).map((u,i)=><img key={i} src={u}/>)}</div></section>}<div className="content-grid"><Block title="🥣 Nguyên liệu" text={detail.ingredients}/><Block title="👩‍🍳 Cách làm" text={detail.steps}/></div><Block title="💡 Lưu ý / Kinh nghiệm" text={detail.notes}/><Block title="📄 Nội dung gốc" text={detail.original_text}/></div></div></div>}
 </div>
}

function Stat({label,value}){return <div className="stat"><small>{label}</small><b>{value}</b></div>}
function Field({label,full,children}){return <label className={full?'field full':'field'}><span>{label}</span>{children}</label>}
function Block({title,text}){return <section className="block"><h3>{title}</h3><div className="pre">{text||'—'}</div></section>}
function Card({recipe,onOpen}){const imgs=imagesOf(recipe);return <article className="card" onClick={onOpen}><div className="cover">{imgs[0]?<img src={imgs[0]}/>:'🍰'}<span className="badge">{recipe.category}</span><span className="heart">{recipe.favorite?'❤️':'♡'}</span></div><div className="card-body"><h3>{recipe.name}</h3><div className="muted">{recipe.version||'V1'} · {imgs.length} ảnh · {recipe.source||'Không ghi nguồn'}</div></div></article>}
function imagesOf(r){return r.recipe_images?r.recipe_images.map(x=>x.image_url):(r.images||[])}
function toDataUrl(file){return new Promise((resolve,reject)=>{const rd=new FileReader();rd.onload=()=>resolve(rd.result);rd.onerror=reject;rd.readAsDataURL(file)})}
function sample(){return[{id:crypto.randomUUID(),name:'Sốt phô mai hoàng kim',category:'Lava / Nhân',source:'Facebook',author:'',version:'V1',rating:5,yield_text:'1 mẻ',time_text:'30 phút',tags:'trứng muối; phô mai; sốt',ingredients:'PHẦN 1\n- 14 trứng muối\n- 70–75 g sữa đặc\n- 70–75 g đường\n- 410 g sữa tươi\n- 100 g whipping',steps:'Xử lý phần 1\nTrộn phần 2\nNấu lửa nhỏ đến khi sệt\nCho bơ vào sau cùng',notes:'Không nấu lửa quá lớn.',original_text:'Dán nguyên văn nội dung Facebook tại đây.',favorite:true,tested:true,images:[]}]}
